### ISSUE TITLE
readme 文档

### ISSUE THREAD

**Issue by Ryan2206** [Bachery/flomo2Readwise#1]
您好开发者，能否出一个相对小白友好的 readme 文档，感谢！

**Comment by Bachery** [comment]
你好，感谢关注。这个方案需要通过Notion中转，先把flomo同步到Notion，再从Notion的数据库中发送到Readwise，如果你有使用Notion的话我可以整理一下。

**Comment by Bachery** [comment]
你好，Readme 文档已更新。目前这只是基于我个人需求写的，使用中如果有什么问题或需求欢迎提出。
