### ISSUE TITLE
同步失败

### ISSUE THREAD

**Issue by Ryan2206** [Bachery/flomo2Readwise#2]
![image](https://github.com/Bachery/flomo2Readwise/assets/80443876/f6a777f9-cccc-4b7f-b014-a0524bf7d738)

**Comment by Bachery** [comment]
奇怪，这看起来像是`last_sync_time.txt`变成了一个只有一个换行符的空文件。首次执行前请确保删除`last_sync_time.txt`和`flomo2readwise.log`这两个文件。
